version: "3"
services:
    ingress:
      build: 
        context: ./ingress/
        dockerfile: Dockerfile
      ports:
        - 80:80
    db:
      build: 
        context: ./db/
        dockerfile: Dockerfile
      ports:
        - 5432:5432
      healthcheck:
        test: pg_isready --username=admin --host=db --dbname=tpa
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 20s