version: "3"
services:
    ingress:
      build: 
        context: ./ingress/
        dockerfile: Dockerfile
      env_file:
        - ./ingress/.env
      ports:
        - 80:80
      depends_on:
        db:
          condition: "service_healthy"
    db:
      build: 
        context: ./db/
        dockerfile: Dockerfile
      ports:
        - 5432:5432
      env_file:
        - ./db/.env
      healthcheck:
        test: pg_isready --username=ingress_admin --host=db --dbname=events
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 20s
      volumes:
        - ./db/data:/var/lib/postgres/data

    nats1:
        image: nats:alpine
        ports:
          - "4222:4222"
          - "8222:8222"      
        volumes:
          - nats1:/data
        command:
          - "--name=nats1"
          - "--cluster_name=c1"
          - "--cluster=nats://nats1:6222"
          - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
          - "--http_port=8222"
          - "--js"
          - "--sd=/data"

    nats2:
      image: nats:alpine
      ports:
        - "4223:4222"
        - "8223:8222"
      volumes:
        - nats2:/data
      command:
        - "--name=nats2"
        - "--cluster_name=c1"
        - "--cluster=nats://nats2:6222"
        - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
        - "--http_port=8222"
        - "--js"
        - "--sd=/data"

    nats3:
      image: nats:alpine
      ports:
        - "4224:4222"
        - "8224:8222"
      volumes:
        - nats3:/data
      command:
        - "--name=nats3"
        - "--cluster_name=c1"
        - "--cluster=nats://nats3:6222"
        - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
        - "--http_port=8222"
        - "--js"
        - "--sd=/data"

volumes:
  nats1:
    external: true
  nats2:
    external: true
  nats3:
    external: true